package events;

public class IXPNEvents {

public static final String a="a";

    public static final String OKCREDIT_LOGO="OKCREDIT_LOGO";
    public static final String SELECT_LANGUAGE_TITLE="SELECT_LANGUAGE_TITLE";
    public static final String SELECT_LANGUAGE_HINDI_BUTTON="SELECT_LANGUAGE_HINDI_BUTTON";
    public static final String SELECT_LANGUAGE_HINGLISH_BUTTON="SELECT_LANGUAGE_HINGLISH_BUTTON";
    public static final String SELECT_LANGUAGE_PUNJABI_BUTTON="SELECT_LANGUAGE_PUNJABI_BUTTON";
    public static final String SELECT_LANGUAGE_ENGLISH_BUTTON="SELECT_LANGUAGE_ENGLISH_BUTTON";
    public static final String SELECT_LANGUAGE_MALAYALAM_BUTTON="SELECT_LANGUAGE_MALAYALAM_BUTTON";


    public static final String WELCOME_SLIDER_PAGE_1_TITLE="WELCOME_SLIDER_PAGE_1_TITLE";
    public static final String WELCOME_SLIDER_PAGE_2_TITLE="WELCOME_SLIDER_PAGE_2_TITLE";
    public static final String WELCOME_SLIDER_PAGE_3_TITLE="WELCOME_SLIDER_PAGE_3_TITLE";
    public static final String WELCOME_SLIDER_PAGE_4_TITLE="WELCOME_SLIDER_PAGE_4_TITLE";
    public static final String WELCOME_SLIDER_PAGE_1_LABEL_SWIPE_TO_LEARN_MORE="WELCOME_SLIDER_PAGE_1_LABEL_SWIPE_TO_LEARN_MORE";
    public static final String WELCOME_SLIDER_PAGE_GET_STARTED_BUTTON="WELCOME_SLIDER_PAGE_GET_STARTED_BUTTON";
    public static final String SIGN_UP_PAGE_PHONE_NUMBER_FIELD="SIGN_UP_PAGE_PHONE_NUMBER_FIELD";
    public static final String SIGN_IN_PAGE_PASSWORD_FIELD="SIGN_IN_PAGE_PASSWORD_FIELD";
    public static final String SIGN_UP_PAGE_FORGET_PASSWORD_BUTTON="SIGN_UP_PAGE_FORGET_PASSWORD_BUTTON";
    public static final String  FORGET_PASSWORD_PAGE_ENTER_OTP="FORGET_PASSWORD_PAGE_ENTER_OTP";
    public static final String  RESET_PASSWORD_PAGE_ENTER_NEW_PASSWORD_FIELD="RESET_PASSWORD_PAGE_ENTER_NEW_PASSWORD_FIELD";
    public static final String HOME_PAGE_USERNAME_TITLE="HOME_PAGE_USERNAME_TITLE";
    public static final String HOME_PAGE_SEARCH_FIELD="HOME_PAGE_SEARCH_FIELD";
    public static final String HOME_PAGE_REFERSH_BUTTON="HOME_PAGE_REFERSH_BUTTON";
    public static final String HOME_PAGE_FILTER_ICON="HOME_PAGE_FILTER_ICON";
    public static final String HOME_PAGE_HAMBURGER_ICON="HOME_PAGE_HAMBURGER_ICON";
    public static final String HOME_PAGE_FILTER_LIST_BY_NAME="HOME_PAGE_FILTER_LIST_BY_NAME";
    public static final String HOME_PAGE_FILTER_LIST_BY_AMOUNT="HOME_PAGE_FILTER_LIST_BY_AMOUNT";
    public static final String HOME_PAGE_FILTER_LIST_BY_LATEST="HOME_PAGE_FILTER_LIST_BY_LATEST";
    public static final String HOME_PAGE_FILTER_LIST_BY_PAYMENT_DUE="HOME_PAGE_FILTER_LIST_BY_PAYMENT_DUE";
    public static final String HOME_PAGE_ADD_YOUR_FIRST_CUSTOMER_TITLE="HOME_PAGE_ADD_YOUR_FIRST_CUSTOMER_TITLE";
    public static final String HOME_PAGE_ADD_CUSTOMER_BUTTON="HOME_PAGE_ADD_CUSTOMER_BUTTON";

    public static final String OK_BUTTON="OK_BUTTON";
    public static final String SIGN_UP_SEND_OTP_BUTTON="SIGN_UP_SEND_OTP_BUTTON";
    public static final String SIGN_UP_OTP_NUMBER_BLOCKS="SIGN_UP_OTP_NUMBER_BLOCKS";
    public static final String SIGN_UP_BY_WHATSAPP_BUTTON="SIGN_UP_BY_WHATSAPP_BUTTON";
    public static final String SIGN_UP_USERNAME_FIELD="SIGN_UP_USERNAME_FIELD";


    public static final String ADD_CUSTOMER_NAME_FIELD="ADD_CUSTOMER_NAME_FIELD";
    public static final String ADD_CUSTOMER_SAVE_NAME_FIELD="ADD_CUSTOMER_SAVE_NAME_FIELD";
    public static final String ADD_CUSTOMER_NUMBER_FIELD="ADD_CUSTOMER_NUMBER_FIELD";
    public static final String ADD_CUSTOMER_SAVE_PHONE_NUMBER_FIELD="ADD_CUSTOMER_SAVE_PHONE_NUMBER_FIELD";

    public static final String CUSTOMER_PAGE_ACCEPT_PAYMENT="CUSTOMER_PAGE_ACCEPT_PAYMENT";
    public static final String CUSTOMER_PAGE_GIVE_CREDIT="CUSTOMER_PAGE_GIVE_CREDIT";

    public static final String ADD_CREDIT_PAGE_AMOUNT_FIELD="ADD_CREDIT_PAGE_AMOUNT_FIELD";
    public static final String ADD_CREDIT_PAGE_ADD_NOTE_FIELD="ADD_CREDIT_PAGE_ADD_NOTE_FIELD";
    public static final String ADD_CREDIT_PAGE_SAVE_BUTTON="ADD_CREDIT_PAGE_SAVE_BUTTON";

    public static final String ADD_CREDIT_PAGE_ALLOW_PHOTO_BUTTON="ADD_CREDIT_PAGE_ALLOW_PHOTO_BUTTON";
    public static final String ADD_CREDIT_PAGE_IMAGE_ATTACHMENT_BUTTON="ADD_CREDIT_PAGE_IMAGE_ATTACHMENT_BUTTON";
    public static final String ADD_CREDIT_PAGE_USE_CAMERA_BUTTON="ADD_CREDIT_PAGE_USE_CAMERA_BUTTON";

    public static final String DEVICE_PERMISSON_OK_BUTTON="DEVICE_PERMISSON_OK_BUTTON";


}
